/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package valentic.registracija.view;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import valentic.registracija.controller.KontrolaUnosa;
import valentic.registracija.controller.ObradaStrankeIVozila;
import valentic.registracija.model.Vozilo;

/**
 *
 * @author Basic
 */
public class OstaliPodaciVozila extends javax.swing.JFrame {

    private Vozilo vozilo;
    private SimpleDateFormat sdf;
    private ObradaStrankeIVozila obr;
    private int sifra;
    private KontrolaUnosa ku;

    /**
     * Creates new form OstaliPodaciOVozilu
     */
    public OstaliPodaciVozila() {
        initComponents();
        sdf = new SimpleDateFormat("dd.MM.yyyy");

        obr = new ObradaStrankeIVozila();
        grupaIspravno.add(ispravnoDa);
        grupaIspravno.add(ispravnoNe);
        ispravnoNe.setSelected(true);
        ku = new KontrolaUnosa();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupaIspravno = new javax.swing.ButtonGroup();
        jButton9 = new javax.swing.JButton();
        ispravnoNe = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        izmjeniPodatke = new javax.swing.JButton();
        obrisiPodatke = new javax.swing.JButton();
        ispravnoDa = new javax.swing.JRadioButton();
        dodajPodatke = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        brojVrata = new javax.swing.JTextField();
        snagaMotora = new javax.swing.JTextField();
        tezinaVozila = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        brojSasije = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ostalo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valentic/icons/zatvori.png"))); // NOI18N
        jButton9.setText("Zatvori prozor");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zatvoriProzor(evt);
            }
        });

        ispravnoNe.setText("Neispravno");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valentic/icons/vozila.png"))); // NOI18N
        jLabel11.setText("Ostali podaci o vozilu");

        izmjeniPodatke.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        izmjeniPodatke.setForeground(new java.awt.Color(255, 51, 0));
        izmjeniPodatke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valentic/icons/izmjeni.png"))); // NOI18N
        izmjeniPodatke.setText("Izmjeni podatke");
        izmjeniPodatke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        izmjeniPodatke.setIconTextGap(12);
        izmjeniPodatke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmjeniPodatkeActionPerformed(evt);
            }
        });

        obrisiPodatke.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        obrisiPodatke.setForeground(new java.awt.Color(255, 0, 0));
        obrisiPodatke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valentic/icons/obrisi2.png"))); // NOI18N
        obrisiPodatke.setText("Obriši podatke");
        obrisiPodatke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        obrisiPodatke.setIconTextGap(12);
        obrisiPodatke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiPodatkeActionPerformed(evt);
            }
        });

        ispravnoDa.setText("Ispravno");

        dodajPodatke.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dodajPodatke.setForeground(new java.awt.Color(255, 0, 0));
        dodajPodatke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valentic/icons/dodaj2.png"))); // NOI18N
        dodajPodatke.setText("Dodaj podatke");
        dodajPodatke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dodajPodatke.setIconTextGap(12);
        dodajPodatke.setVerifyInputWhenFocusTarget(false);
        dodajPodatke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajPodatkeActionPerformed(evt);
            }
        });

        jLabel5.setText("Broj vrata");

        jLabel6.setText("Broj šasije( obavezan unos)");

        jLabel9.setText("SnagaMotora(u konjskim snagama)");

        jLabel10.setText("Težina vozila (decimalni zapis)");

        jLabel7.setText("Ostalo");

        ostalo.setColumns(20);
        ostalo.setRows(5);
        jScrollPane1.setViewportView(ostalo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(snagaMotora, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brojVrata)
                            .addComponent(tezinaVozila, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brojSasije, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dodajPodatke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(obrisiPodatke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(izmjeniPodatke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ispravnoDa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ispravnoNe))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(9, 9, 9)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(brojSasije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dodajPodatke)
                        .addGap(18, 18, 18)
                        .addComponent(izmjeniPodatke)
                        .addGap(26, 26, 26)
                        .addComponent(obrisiPodatke)
                        .addGap(18, 18, 18)
                        .addComponent(ispravnoDa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ispravnoNe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jButton9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(snagaMotora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tezinaVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brojVrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajPodatkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajPodatkeActionPerformed

        if (!ku.provjeraUnosaID(brojSasije) || !ku.provjeraUnosaKonjskihsnaga(snagaMotora) || !ku.provjeraUnosaZaDecimalniZapis(tezinaVozila) || !ku.provjeraUnosaVrata(brojVrata)) {
            return;
        }

        postaviPoljaOstalihPodatakVozila(vozilo);

        if (ispravnoNe.isSelected()) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Ukoliko želite dodati ostale podatke označite ispravnost odabira!",
                    "Pogreška",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            if (obr.dodajOstaleVozila(vozilo)) {

                JOptionPane.showMessageDialog(
                        rootPane,
                        "Uspješno dodani ostali podaci! ",
                        "Poruka",
                        JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Pogreška kod dodavanja podataka!",
                        "Greška",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_dodajPodatkeActionPerformed

    private void izmjeniPodatkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmjeniPodatkeActionPerformed

        if (!ku.provjeraUnosaID(brojSasije) || !ku.provjeraUnosaKonjskihsnaga(snagaMotora) || !ku.provjeraUnosaZaDecimalniZapis(tezinaVozila) || !ku.provjeraUnosaVrata(brojVrata)) {
            return;
        }

        postaviPoljaOstalihPodatakVozila(vozilo);

        if (ispravnoNe.isSelected()) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Ukoliko želite izmjeniti ostale podatke označite ispravnost odabira!",
                    "Pogreška",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            if (obr.izmjeniOstaleVozila(vozilo)) {

                JOptionPane.showMessageDialog(
                        rootPane,
                        "Uspješno izmjenjeni ostali podaci! ",
                        "Poruka",
                        JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Pogreška kod izmjene podataka!",
                        "Greška",
                        JOptionPane.ERROR_MESSAGE);
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_izmjeniPodatkeActionPerformed

    private void obrisiPodatkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiPodatkeActionPerformed

        Object[] options = {"Da", "Ne, vrati se nazad",};

        int izbor = JOptionPane.showOptionDialog(rootPane, "Da li stvarno želite obrisati ostale podatke o Vozilu ??", "Sistem", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (ispravnoNe.isSelected()) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Ukoliko želite obrisati podatke označite ispravnost odabira!",
                    "Obavijest",
                    JOptionPane.ERROR_MESSAGE);
        } else if (izbor == 0) {
            if (obr.obrisiOstaleVozila(vozilo)) {

                JOptionPane.showMessageDialog(
                        rootPane,
                        "Uspješno obrisani podaci! ",
                        "Obavijest",
                        JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Pogreška kod brisanja podataka!",
                        "Greška",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_obrisiPodatkeActionPerformed

    private void zatvoriProzor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zatvoriProzor
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_zatvoriProzor

    /**
     * @param args the command line arguments
     */
    void setVozilo(Vozilo vozilo) {
        this.vozilo = vozilo;
    }

    void popuniPolja(Vozilo vozilo) {

        if (vozilo.getBrojSasije() == null) {
            brojSasije.setText("");
        } else {
            brojSasije.setText(vozilo.getBrojSasije());
        }

        if (vozilo.getSnagaMotora() == 0) {
            snagaMotora.setText(null);
        } else {
            snagaMotora.setText(Integer.toString(vozilo.getSnagaMotora()));
        }

        if (vozilo.getTezinaVozila() == 0) {
            tezinaVozila.setText("");
        } else {
            tezinaVozila.setText(Double.toString(vozilo.getTezinaVozila()));
        }

        if (vozilo.getBrojVrata() == 0) {
            brojVrata.setText("");
        } else {
            brojVrata.setText(Integer.toString(vozilo.getBrojVrata()));
        }

        if (vozilo.getOstalo() == null) {
            ostalo.setText("");
        } else {
            ostalo.setText(vozilo.getOstalo());
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brojSasije;
    private javax.swing.JTextField brojVrata;
    private javax.swing.JButton dodajPodatke;
    private javax.swing.ButtonGroup grupaIspravno;
    private javax.swing.JRadioButton ispravnoDa;
    private javax.swing.JRadioButton ispravnoNe;
    private javax.swing.JButton izmjeniPodatke;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton obrisiPodatke;
    private javax.swing.JTextArea ostalo;
    private javax.swing.JTextField snagaMotora;
    private javax.swing.JTextField tezinaVozila;
    // End of variables declaration//GEN-END:variables

    private void postaviPoljaOstalihPodatakVozila(Vozilo vozilo) {
        try {

            vozilo.setBrojSasije(brojSasije.getText());
        } catch (Exception e) {
            vozilo.setBrojSasije(null);

        }

        try {
            vozilo.setSnagaMotora(Integer.parseInt(snagaMotora.getText()));
        } catch (Exception e) {
            vozilo.setSnagaMotora(0);
        }

        try {
            vozilo.setTezinaVozila(Double.parseDouble(tezinaVozila.getText()));
        } catch (Exception e) {
            vozilo.setTezinaVozila(Double.parseDouble("0.0"));
        }

        try {
            vozilo.setBrojVrata(Integer.parseInt(brojVrata.getText()));
        } catch (Exception e) {
            vozilo.setBrojVrata(0);
        }

        try {
            vozilo.setOstalo(ostalo.getText());
        } catch (Exception e) {
            vozilo.setOstalo(null);
        }
    }

}
