/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package valentic.registracija.view;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import valentic.registracija.controller.KontrolaUnosa;
import valentic.registracija.controller.ObradaStrankeIVozila;
import valentic.registracija.model.Stranka;

/**
 *
 * @author Basic
 */
public class OstaliPodaciStranke extends javax.swing.JFrame {

    private ObradaStrankeIVozila obradaGlavniProzor;
    private Stranka stranka;
    private SimpleDateFormat sdf;
    private int sifra;

    private KontrolaUnosa ku;

    /**
     * Creates new form OstaliPodaciStranke
     */
    public OstaliPodaciStranke() {
        initComponents();

        obradaGlavniProzor = new ObradaStrankeIVozila();
        //sdf.setLenient(false);
        sdf = new SimpleDateFormat("dd.MM.yyyy");
        grupaIspravnoOst.add(ispravnoDa);
        grupaIspravnoOst.add(ispravnoNe);
        ispravnoNe.setSelected(true);
        ku = new KontrolaUnosa();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupaIspravnoOst = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fiksnitelefon = new javax.swing.JTextField();
        drzava = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        grad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adresa2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        drugimobitel = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ispravnoNe = new javax.swing.JRadioButton();
        zatvoriProzor = new javax.swing.JButton();
        dodajPodatke = new javax.swing.JButton();
        ispravnoDa = new javax.swing.JRadioButton();
        obrisiStranku = new javax.swing.JButton();
        izmjeniStranku = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        datumrodjenja = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        zip = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        regija = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jLabel8.setText("Datum rođenja (dd.MM.yyyy)");

        jLabel2.setText("Druga adresa");

        jLabel7.setText("Grad");

        jLabel5.setText("Fiksni tel. (+385/xxx-xxx-xxxx)");

        jLabel4.setText("email   (korisnik@domena.com)");

        jLabel6.setText("Država");

        jLabel3.setText("drugi mobitel (+385/xxx-xxx-xxxx)");

        jLabel17.setText("Ispravno");

        ispravnoNe.setText("Ne");

        zatvoriProzor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valentic/icons/zatvori.png"))); // NOI18N
        zatvoriProzor.setText("Zatvori prozor");
        zatvoriProzor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zatvoriProzorActionPerformed(evt);
            }
        });

        dodajPodatke.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dodajPodatke.setForeground(new java.awt.Color(255, 0, 0));
        dodajPodatke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valentic/icons/dodaj2.png"))); // NOI18N
        dodajPodatke.setText("Dodaj podatke");
        dodajPodatke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dodajPodatke.setIconTextGap(12);
        dodajPodatke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajPodatkeActionPerformed(evt);
            }
        });

        ispravnoDa.setText("Da");

        obrisiStranku.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        obrisiStranku.setForeground(new java.awt.Color(255, 0, 0));
        obrisiStranku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valentic/icons/obrisi2.png"))); // NOI18N
        obrisiStranku.setText("Obriši podatke");
        obrisiStranku.setHideActionText(true);
        obrisiStranku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        obrisiStranku.setIconTextGap(12);
        obrisiStranku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiStrankuActionPerformed(evt);
            }
        });

        izmjeniStranku.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        izmjeniStranku.setForeground(new java.awt.Color(255, 0, 0));
        izmjeniStranku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valentic/icons/izmjeni.png"))); // NOI18N
        izmjeniStranku.setText("Izmjeni podatke");
        izmjeniStranku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        izmjeniStranku.setIconTextGap(12);
        izmjeniStranku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmjeniStrankuActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valentic/icons/stranka.png"))); // NOI18N
        jLabel11.setText("Ostali podaci o stranci");

        jLabel1.setText("Zip (xxxxx)");

        jLabel9.setText("Regija");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(regija, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zip, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datumrodjenja, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adresa2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drugimobitel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(drzava, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fiksnitelefon)
                            .addComponent(grad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ispravnoDa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ispravnoNe))
                            .addComponent(obrisiStranku, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dodajPodatke, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(izmjeniStranku, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zatvoriProzor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datumrodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adresa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dodajPodatke, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugimobitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izmjeniStranku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiksnitelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrisiStranku))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(ispravnoNe)
                            .addComponent(ispravnoDa))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(zatvoriProzor))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajPodatkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajPodatkeActionPerformed
        

        if (!ku.provjeraUnosaZipa(zip) || !ku.provjeraUnosaNaziva(regija) || !ku.provjeraUnosaNaziva(drzava) || !ku.provjeraUnosaNaziva(grad) || !ku.provjeraUnosaAdrese(adresa2) || !ku.provjeraUnosaZaDatum(datumrodjenja) || !ku.provjeraUnosaZaMobitel(drugimobitel) || !ku.provjeraUnosFiksnog(fiksnitelefon) || !ku.provjeraUnosaZaMail(email)) {

            return;
        }

        postaviPoljaOstalihPodatakaStranke(stranka);

        if (ispravnoNe.isSelected()) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Ukoliko želite dodati ostalepodatke označite ispravnost odabira!",
                    "Pogreška",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            if (obradaGlavniProzor.dodajOstaleStranke(stranka)) {

                JOptionPane.showMessageDialog(
                        rootPane,
                        "Uspješno dodani podaci! ",
                        "Poruka",
                        JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Pogreška kod dodavanja podataka!",
                        "Greška",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_dodajPodatkeActionPerformed

    private void obrisiStrankuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiStrankuActionPerformed

        if (ispravnoNe.isSelected()) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Ukoliko želite obrisati podatke stranke odaberite ispravnost odabira!",
                    "Pogreška",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            if (obradaGlavniProzor.obrisiOstaleStranke(stranka)) {

                
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Uspješno ste obrisali ostale podatke o stranci",
                        "Poruka",
                        JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Pogreška kod brisanja",
                        "Greška",
                        JOptionPane.ERROR_MESSAGE);
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_obrisiStrankuActionPerformed

    private void izmjeniStrankuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmjeniStrankuActionPerformed

       

        if (!ku.provjeraUnosaZipa(zip) || !ku.provjeraUnosaNaziva(regija) || !ku.provjeraUnosaNaziva(drzava) || !ku.provjeraUnosaNaziva(grad) || !ku.provjeraUnosaAdrese(adresa2) || !ku.provjeraUnosaZaDatum(datumrodjenja) || !ku.provjeraUnosaZaMobitel(drugimobitel) || !ku.provjeraUnosFiksnog(fiksnitelefon) || !ku.provjeraUnosaZaMail(email)) {

            return;
        }

        postaviPoljaOstalihPodatakaStranke(stranka);

        if (ispravnoNe.isSelected()) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Ukoliko želite izmjeniti podatke stranke odaberite ispravnost odabira",
                    "Pogreška",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            if (obradaGlavniProzor.izmjeniOstaleStranke(stranka)) {

                
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Uspješno izmjena podataka",
                        "Poruka",
                        JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Pogreška kod izmjene podataka",
                        "Greška",
                        JOptionPane.ERROR_MESSAGE);
            }
        }// TODO add your handling code here:

    }//GEN-LAST:event_izmjeniStrankuActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void zatvoriProzorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zatvoriProzorActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_zatvoriProzorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresa2;
    private javax.swing.JFormattedTextField datumrodjenja;
    private javax.swing.JButton dodajPodatke;
    private javax.swing.JTextField drugimobitel;
    private javax.swing.JTextField drzava;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fiksnitelefon;
    private javax.swing.JTextField grad;
    private javax.swing.ButtonGroup grupaIspravnoOst;
    private javax.swing.JRadioButton ispravnoDa;
    private javax.swing.JRadioButton ispravnoNe;
    private javax.swing.JButton izmjeniStranku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton obrisiStranku;
    private javax.swing.JTextField regija;
    private javax.swing.JButton zatvoriProzor;
    private javax.swing.JTextField zip;
    // End of variables declaration//GEN-END:variables

    void popuniPolja(Stranka stranka) {

        if (stranka.getAdresa2() == null) {
            adresa2.setText("");
        } else {
            adresa2.setText(stranka.getAdresa2());
        }

        if (stranka.getDrugiMobitel() == null) {
            drugimobitel.setText("");
        } else {
            drugimobitel.setText(stranka.getDrugiMobitel());
        }

        if (stranka.getFiksniTelefon() == null) {
            fiksnitelefon.setText("");
        } else {
            fiksnitelefon.setText(stranka.getFiksniTelefon());
        }

        if (stranka.getEmail() == null) {
            email.setText("");
        } else {
            email.setText(stranka.getEmail());
        }

        if (stranka.getDrzava() == null) {
            drzava.setText("");
        } else {
            drzava.setText(stranka.getDrzava());
        }

        if (stranka.getGrad() == null) {
            grad.setText("");
        } else {
            grad.setText(stranka.getGrad());
        }

        if (stranka.getZip() == 0) {
            zip.setText("");
        } else {
            zip.setText(Integer.toString(stranka.getZip()));
        }

        if (stranka.getRegija() == null) {
            regija.setText("");
        } else {
            regija.setText(stranka.getRegija());
        }

        if (stranka.getDatumRodjenja() == null) {
            datumrodjenja.setText("");
        } else {
            datumrodjenja.setText(sdf.format(stranka.getDatumRodjenja()));
        }

    }

    void setStranka(Stranka stranka) {
        this.stranka = stranka;
    }

    private void postaviPoljaOstalihPodatakaStranke(Stranka stranka) {

        DateFormat format = sdf;
        try {
            stranka.setDatumRodjenja(format.parse(datumrodjenja.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Datum mora biti u formatu (dd.mm.yyyy)!",
                    "Pogreška",
                    JOptionPane.ERROR_MESSAGE);
            return;

        }

        try {
            stranka.setAdresa2(adresa2.getText());
        } catch (Exception e) {
            stranka.setAdresa2(null);
        }
        try {
            stranka.setDrugiMobitel(drugimobitel.getText());
        } catch (Exception e) {
            stranka.setDrugiMobitel(null);
        }

        try {
            stranka.setFiksniTelefon(fiksnitelefon.getText());
        } catch (Exception e) {
            stranka.setFiksniTelefon(null);
        }

        try {
            stranka.setEmail(email.getText());
        } catch (Exception e) {
            stranka.setEmail(null);
        }

        try {
            stranka.setDrzava(drzava.getText());
        } catch (Exception e) {
            stranka.setDrzava(null);
        }

        try {
            stranka.setGrad(grad.getText());
        } catch (Exception e) {
            stranka.setGrad(null);
        }

        try {
            stranka.setZip(Integer.parseInt(zip.getText()));
        } catch (Exception e) {
            stranka.setZip(0);
        }

        try {
            stranka.setRegija(regija.getText());
        } catch (Exception e) {
            stranka.setRegija(null);
        }
    }

   

}
